final familyData = [
  {"name": "Tom", "relation": "Cousin", "age": 28},
  {"name": "Lily", "relation": "Aunt", "age": 45},
  {"name": "Jack", "relation": "Uncle", "age": 50},
  {"name": "Emma", "relation": "Sister", "age": 22},
  {"name": "Oliver", "relation": "Brother", "age": 30},
  {"name": "Sophia", "relation": "Cousin", "age": 25},
  {"name": "William", "relation": "Grandfather", "age": 75},
  {"name": "Mia", "relation": "Cousin", "age": 20},
  {"name": "Ethan", "relation": "Nephew", "age": 10},
  {"name": "Ava", "relation": "Niece", "age": 8},
  {"name": "James", "relation": "Brother", "age": 28},
  {"name": "Charlotte", "relation": "Sister", "age": 32},
  {"name": "Benjamin", "relation": "Cousin", "age": 30},
  {"name": "Amelia", "relation": "Cousin", "age": 27},
  {"name": "Daniel", "relation": "Father", "age": 55},
  {"name": "Sofia", "relation": "Mother", "age": 52},
  {"name": "Logan", "relation": "Cousin", "age": 29},
  {"name": "Harper", "relation": "Niece", "age": 12},
  {"name": "Michael", "relation": "Cousin", "age": 26},
  {"name": "Evelyn", "relation": "Sister", "age": 24}
];
