final relativesData = [
  {"name": "Tom", "relation": "Cousin", "age": 28},
  {"name": "Lily", "relation": "Aunt", "age": 45},
  {"name": "John", "relation": "Uncle", "age": 50},
  {"name": "Emily", "relation": "Niece", "age": 18},
  {"name": "William", "relation": "Cousin", "age": 32},
  {"name": "Olivia", "relation": "Cousin", "age": 30},
  {"name": "James", "relation": "Cousin", "age": 29},
  {"name": "Sophia", "relation": "Aunt", "age": 55},
  {"name": "Benjamin", "relation": "Uncle", "age": 48},
  {"name": "Ava", "relation": "Niece", "age": 21},
  {"name": "Mason", "relation": "Cousin", "age": 27},
  {"name": "Amelia", "relation": "Cousin", "age": 31},
  {"name": "Elijah", "relation": "Cousin", "age": 26},
  {"name": "Charlotte", "relation": "Aunt", "age": 60},
  {"name": "Ethan", "relation": "Uncle", "age": 52},
  {"name": "Mia", "relation": "Niece", "age": 23},
  {"name": "Alexander", "relation": "Cousin", "age": 25},
  {"name": "Harper", "relation": "Cousin", "age": 29},
  {"name": "Daniel", "relation": "Cousin", "age": 30},
  {"name": "Evelyn", "relation": "Aunt", "age": 58},
];
